### ISSUE TITLE
Cannot handle push when app in background in iOS

### ISSUE THREAD

**Issue by nhanv** [Pushwoosh/pushwoosh-flutter#24] opened 2020-03-10 11:37 UTC
I'm using latest version 1.20.0. This case worked on android but not work on iOS:
1. App is running in foreground
2. Received new push
3. Open multitask and swipe to close app
4. Click on notification in Notification Tray
5. App open but I cannot receive data push in Pushwoosh.getInstance.onPushReceived to handle action.

Can you check it or guide for me how to handle push on this case.
Thank you.

**Comment by wfhm** [comment] 2020-03-10 16:47
Hi @nhanv,

Checking it.

**Comment by wfhm** [comment] 2020-03-13 14:17
@nhanv,

Confirmed, the issue is on our side. First, we have to fix it in native iOS SDK, then, the plugin will be updated.

**Comment by wfhm** [comment] 2020-03-25 15:46
@nhanv,

Fixed with the latest release.

**Closed as completed by wfhm** 2020-03-25 15:46 UTC
Labels: 47830
