### ISSUE TITLE
Empty notification appears when dismissing exisiting notifications

### ISSUE THREAD

**Issue by Ayush783** [Pushwoosh/pushwoosh-flutter#82] opened 2024-05-13 10:39 UTC
Platform - Android

Steps to reproduce:

* I triggered two notifications using createMessage API from Postman when the app is in background.
* Now kill the app and trigger one more notification.
* Now when you clear all the notifications from the tray, A blank notification appears.

I'm unable to figure out the exact reason behind this, will require immediate assistance.

Thanks!

**Comment by enginseer-dev** [comment] 2024-05-13 12:59
Hello, @Ayush783 

I couldn't replicate the issue where a blank notification appears after clearing them.
Could you please specify the Pushwoosh plugin version and the device used for testing?
Also, does this issue occur if you build our sample Flutter app?

You can find the sample app here: https://github.com/Pushwoosh/pushwoosh-flutter-sample

**Comment by Ayush783** [comment] 2024-05-14 04:49
Let me check, will get back to you soon

**Comment by Ayush783** [comment] 2024-05-14 05:19
Hi @enginseer-dev 
I ran your sample app. You need to setMultiNotificationMode to true and follow the repro steps above.
You will get a blank notification.

Please do let me know if you need a recording of this as well

**Comment by enginseer-dev** [comment] 2024-05-14 08:31
Thank you, @Ayush783 We were able to reproduce the issue.
I'll update you as soon as we find the source of the problem.

**Comment by Ayush783** [comment] 2024-05-16 05:19
Hi @enginseer-dev, Just wanted to follow up on this issue, also can you please ask someone from your team to update the progress on the mail thread I started, [#88183](https://help.pushwoosh.com/hc/requests/88183) as my seniors are also involved in that conversation

**Comment by kaushalkaajtak** [comment] 2024-05-20 05:23
Hi @enginseer-dev, were you guys able to figure out the reason for blank notifications?

**Comment by enginseer-dev** [comment] 2024-05-20 05:44
Hello, @kaushalkaajtak, @Ayush783
Yes, we were able to reproduce the issue and are working on a fix.
I will update you as soon as the new version of the plugin is released.

**Comment by kaushalkaajtak** [comment] 2024-05-20 06:23
Hi @enginseer-dev, thanks for the update. Can you please share ETA for the issue as we have a build waiting to go live because of this.

**Comment by enginseer-dev** [comment] 2024-05-20 13:27
@kaushalkaajtak We have identified the root cause of the issue and are working on a solution.
The expected time frame for the fix is approximately one week. 
Thank you for your patience.

**Comment by kaushalkaajtak** [comment] 2024-05-21 04:50
@enginseer-dev our really major update is on hold due to this particular fix, currently elections are going on and we are not able to operate because of delayed update. Please try to close this ASAP.

**Comment by enginseer-dev** [comment] 2024-05-21 11:16
@kaushalkaajtak We understand the urgency of this issue and the impact it has on your operations. 
We are working on the fix, and we expect to release it within this week. 
We are prioritizing this to ensure it's resolved as soon as possible.

**Comment by wfhm** [comment] 2024-05-24 06:58
@kaushalkaajtak @Ayush783 fixed with the latest release.

**Closed as completed by wfhm** 2024-05-24 06:58 UTC
